// <auto-generated />
namespace OnlineFlightbooking.DiL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ticketbook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ticketbook));
        
        string IMigrationMetadata.Id
        {
            get { return "202011071153320_ticketbook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
